---

- ansible.builtin.include_tasks: install.yml
- ansible.builtin.include_tasks: modules.yml
- ansible.builtin.include_tasks: custom_modules.yml
- ansible.builtin.include_tasks: config.yml
- ansible.builtin.include_tasks: setup.yml
