---

- ansible.builtin.include_tasks: install.yml
- ansible.builtin.include_tasks: modules.yml
- ansible.builtin.include_tasks: config.yml

- name: Restart filebeat
  become: true
  ansible.builtin.service:
    name: filebeat
    state: restarted
